### ISSUE TITLE
Print Area of Rectangle by Using Class.

### ISSUE THREAD

**Issue by gmershad** [gmershad/Groks#1]
Print Area, Length, Width of a Rectangle by using Class. 
Below Steps:

1) Open Visual Studio -> File -> New -> Project - >Visual C# -> Console Application.
2) Give the name of your project.
3) Create one Class in your project named with "Rectangle". Class should be Public.
4) Take two properties or variables - double length;  double width;
5) Create three methods or function ->
    a) Acceptdetails
    b) GetArea
    c) Display

6) Now execute the code in Program.cs file by creating object and calling method.

Reference:
http://www.tutorialspoint.com/csharp/csharp_basic_syntax.htm

**Comment by shyamsy** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AreaOfRectangle
{
    class Program
    {
        static void Main(string[] args)
        {
            int Area, height, width;

            Console.Write("Please enter the height of Rectange:");
            height = Convert.ToInt32(Console.ReadLine());

            Console.Write("Please enter the width of rectanle:");
            width = Convert.ToInt32(Console.ReadLine());


            Area = height * width;

            Console.WriteLine("The Area of Rectangle is {0}", Area);

            Console.ReadLine();



        }
        
    }`

**Comment by gmershad** [comment]
Learnt below points:

- How to create class.
- How to call class method to outside.
